application: destiny-db
version: 1
runtime: python27
api_version: 1
default_expiration: 0
instance_class: F2
threadsafe: true

handlers:
- url: /_ah/warmup
  script: dashboard.api.app

- url: /(google38371e7df630b0a7[.]html)
  static_files: dashboard/\1
  upload: google38371e7df630b0a7.html

- url: /(.*[.](css|ico|js|txt))
  static_files: dashboard/\1
  upload: .*[.](css|ico|js|txt)

- url: /.*
  secure: always
  script: dashboard.api.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
