application: nmlorgdev
module: destiny
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 0

handlers:
- url: /.*
  script: main.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
