application: nmlorgdev
module: destiny
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 0

handlers:
- url: /(.*[.](css|ico|js))
  static_files: \1
  upload: .*[.](css|ico|js)

- url: /
  static_files: index.html
  upload: index.html

- url: /data/.*
  script: data.app

- url: /friends.*
  static_files: index.html
  upload: index.html

- url: /user/.*
  script: user.app

- url: /_ah/warmup
  script: user.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
