application: nmlorgdev
module: destiny
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 0

handlers:
- url: /friends.*
  script: friends.app

- url: /user/.*
  script: user.app

- url: /_ah/warmup
  script: user.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
